name: Check
on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - name: Cache Cargo files
        uses: actions/cache@v3.0.10
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-rustfmt--${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1.0.1
        with:
          command: fmt
          args: -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - name: Cache Cargo files
        uses: actions/cache@v3.0.10
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-clippy
      - name: Install toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          components: clippy
          override: true
      - name: Run Clippy
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --verbose -- -D warnings
