name: Release
on:
  push:
    tags: [ v* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - name: Cache Cargo files
        uses: actions/cache@v3.0.10
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Prepare crate
        uses: actions-rs/cargo@v1.0.3
        with:
          command: package
      - name: Login to crates.io
        uses: actions-rs/cargo@v1.0.3
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish crate
        uses: actions-rs/cargo@v1.0.3
        with:
          command: publish

  release:
    name: Build ${{ matrix.os }} binary
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin ]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary-name: comproxity
            artifact-name: comproxity-linux-x86_64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            binary-name: comproxity.exe
            artifact-name: comproxity-windows-x86_64.exe
          - target: x86_64-apple-darwin
            os: macOS-latest
            binary-name: comproxity
            artifact-name: comproxity-darwin-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - name: Cache Cargo files
        uses: actions/cache@v3.0.10
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - name: Build crate
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Move binary
        run: mv target/${{ matrix.target }}/release/${{ matrix.binary-name }} ${{ matrix.artifact-name }}
      - name: Generate checksum
        run: shasum -a 256 ${{ matrix.artifact-name }} > ${{ matrix.artifact-name }}.sha256
      - name: Upload release binary
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact-name }}-*
          file_glob: true
          tag: ${{ github.ref }}

  dockerize:
    name: Dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/comproxity:${{ github.ref }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/comproxity:latest
