name: Release
on:
  push:
    tags: [ v* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  dry-run:
    name: Dry run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - name: Cache Cargo files
        uses: actions/cache@v3.0.10
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Perform dry run
        uses: actions-rs/cargo@v1.0.3
        with:
          command: publish
          args: --dry-run

  build:
    name: Build ${{ matrix.os }} binary
    needs: dry-run
    strategy:
      matrix:
        type: [ linux-x86_64, windows-x86_64, darwin-x86_64 ]
        include:
          - type: linux-x86_64
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary-name: comproxity
            artifact-name: comproxity-linux-x86_64
          - type: windows-x86_64
            target: x86_64-pc-windows-msvc
            os: windows-latest
            binary-name: comproxity.exe
            artifact-name: comproxity-windows-x86_64.exe
          - type: darwin-x86_64
            target: x86_64-apple-darwin
            os: macOS-latest
            binary-name: comproxity
            artifact-name: comproxity-darwin-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - name: Cache Cargo files
        uses: actions/cache@v3.0.10
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - name: Build crate
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Rename artifact
        run: >
          mv target/${{ matrix.target }}/release/${{ matrix.binary-name }}
          target/${{ matrix.target }}/release/${{ matrix.artifact-name }}
      - name: Generate checksum
        run: >
          shasum -a 256 target/${{ matrix.target }}/release/${{ matrix.artifact-name }}
          > target/${{ matrix.target }}/release/${{ matrix.artifact-name }}.sha256
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ matrix.type }}
          path: |
            target/${{ matrix.target }}/release/${{ matrix.artifact-name }}
            target/${{ matrix.target }}/release/${{ matrix.artifact-name }}.sha256

  dockerize:
    name: Dockerize
    needs: dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/comproxity:${{ github.ref_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/comproxity:latest

  release:
    name: Create release
    needs: [ build, dockerize ]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.1
        with:
          path: artifacts
      - name: List artifacts
        run: find artifacts -type f
      - name: Perform release
        uses: softprops/action-gh-release@v0.1.14
        with:
          generate_release_notes: true
          files: artifacts/**

  publish:
    name: Publish to crates.io
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - name: Cache Cargo files
        uses: actions/cache@v3.0.10
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Prepare crate
        uses: actions-rs/cargo@v1.0.3
        with:
          command: package
      - name: Login to crates.io
        uses: actions-rs/cargo@v1.0.3
        with:
          command: login
          args: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish crate
        uses: actions-rs/cargo@v1.0.3
        with:
          command: publish
